
DROP DATABASE IF EXISTS livreaudio;

CREATE DATABASE livreaudio;

USE livreaudio;

DROP TABLE IF EXISTS Theme;

CREATE TABLE Theme (
    Id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Libelle VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS Auteur;

CREATE TABLE Auteur (
    Id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    Prenom VARCHAR(50) NOT NULL,
    DateNaissance DATE DEFAULT
);

DROP TABLE IF EXISTS Livre (
    CREATE TABLE Livre;

Id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Titre VARCHAR(1000) NOT NULL,
Langue VARCHAR(50) NOT NULL,
AnneePublication INT(4) NOT NULL,
IdTheme INT UNSIGNED NOT NULL,
IdAuteur INT UNSIGNED NOT NULL,
FOREIGN KEY (IdAuteur) REFERENCES Auteur(Id),
FOREIGN KEY (IdTheme) REFERENCES Theme(Id)
);